spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # create, update(???)
    show-sql: ${SHOW_SQL:true} # SQL ?? ??(??)
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 587
    username: ${EMAIL} #이메일 발송에 사용할 네이버 아이디 ~~~@naver.com
    password: ${EMAIL_APP_PASSWORD}    # 앱 비밀번호 (계정 비번 아님!) 네이버ID -> 보안설정 -> 2단계 인증 관리 여기서 발급
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: ${SERVER_PORT:8080}

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION:ap-northeast-2}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000} # 1??

logging:
  level:
    root: INFO
    com.sparta.vroomvroom: DEBUG

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-robotics-er-1.5-preview:generateContent"
    key: ${GEMINI_API_KEY}
