spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # create, update(???)
    show-sql: ${SHOW_SQL:true} # SQL ?? ??(??)
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION:ap-northeast-2}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000} # 1??

logging:
  level:
    root: INFO
    com.sparta.vroomvroom: DEBUG