name: CI/CD - dev

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:dev-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}       
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}     
          script: |
            set -e
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:dev-latest
            docker rm -f vroom-vroom || true
            docker run -d --name vroom-vroom \
              -p 80:8080 \
              --env-file ~/.env \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:dev-latest
