name: CI - Build & Push Docker (dev)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dev commit)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - show branch & files
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          git rev-parse --abbrev-ref HEAD
          ls -la
          test -f Dockerfile && echo "OK: Dockerfile found" || (echo "NG: Dockerfile missing"; exit 1)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:dev-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vroom-vroom:${{ github.sha }}
